# Generated by Django 5.2 on 2025-05-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulaire', '0002_participant_delete_submission_delete_uniquelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='boisson',
            field=models.CharField(choices=[('fantan', 'Fantan'), ('coca', 'Coca'), ('vitalo', 'Vitalo'), ('eau', 'Eau'), ('primus', 'Primus'), ('turbo', 'Turbo'), ('nkoyi_likofi', 'Nkoyi Likofi'), ('nkoyi_grand', 'Nkoyi Grand'), ('heineken', 'Heineken'), ('beaufort', 'Beaufort'), ('castel', 'Castel'), ('tembo', 'Tembo')], default='eau', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='boisson_conjoint',
            field=models.CharField(blank=True, choices=[('fantan', 'Fantan'), ('coca', 'Coca'), ('vitalo', 'Vitalo'), ('eau', 'Eau'), ('primus', 'Primus'), ('turbo', 'Turbo'), ('nkoyi_likofi', 'Nkoyi Likofi'), ('nkoyi_grand', 'Nkoyi Grand'), ('heineken', 'Heineken'), ('beaufort', 'Beaufort'), ('castel', 'Castel'), ('tembo', 'Tembo')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='nom_conjoint',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='prenom_conjoint',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
